# Generated by Django 4.2.7 on 2023-11-25 00:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='anime',
            old_name='genero',
            new_name='genre',
        ),
        migrations.RenameField(
            model_name='anime',
            old_name='sinopse',
            new_name='synopsis',
        ),
        migrations.RenameField(
            model_name='anime',
            old_name='titulo',
            new_name='title',
        ),
    ]
