# Generated by Django 4.2.7 on 2023-11-25 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rename_genero_anime_genre_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='anime',
            name='trailer_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
